apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgl-backend
spec:
  selector:
    matchLabels:
      app: sgl-backend
  template:
    metadata:
      labels:
        app: sgl-backend
    spec:
      containers:
      - name: backend
        image: hobson007breno/sgl-backend:5f13018
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/licitacoes"
        - name: PNCP_BASE_URL
          value: "https://pncp.gov.br/api/consulta"
        - name: TZ
          value: "America/Sao_Paulo"
        - name: SERPAPI_KEYS
          valueFrom:
            secretKeyRef:
              name: sgl-secrets
              key: SERPAPI_KEYS
              optional: true
        - name: GOV_BR_USER
          valueFrom:
            secretKeyRef:
              name: sgl-secrets
              key: GOV_BR_USER
              optional: true
        - name: GOV_BR_PASS
          valueFrom:
            secretKeyRef:
              name: sgl-secrets
              key: GOV_BR_PASS
              optional: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: sgl-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
