apiVersion: batch/v1
kind: CronJob
metadata:
  name: sgl-etl-cronjob
spec:
  # Roda às 02:00 da manhã do dia 10 de cada mês
  schedule: "0 2 10 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sgl-etl
            # Substituir pela sua imagem real hospedada no Docker Hub / Registry (ex: breno/sgl-backend:latest)
            image: hobson007breno/sgl-backend:577403d
            command:
            - npm
            - run
            - sync:receita:prod
            env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/licitacoes"
            - name: TZ
              value: "America/Sao_Paulo"
            - name: PNCP_BASE_URL
              value: "https://pncp.gov.br/api/consulta"
            - name: SERPAPI_KEYS
              valueFrom:
                secretKeyRef:
                  name: sgl-secrets
                  key: SERPAPI_KEYS
          restartPolicy: OnFailure
