apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgl-market-intelligence
spec:
  selector:
    matchLabels:
      app: sgl-market-intelligence
  template:
    metadata:
      labels:
        app: sgl-market-intelligence
    spec:
      containers:
      - name: market-intelligence
        image: hobson007breno/sgl-market-intelligence:5b0ce67
        ports:
        - containerPort: 7010
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/licitacoes"
        - name: TZ
          value: "America/Sao_Paulo"
---
apiVersion: v1
kind: Service
metadata:
  name: market-intelligence
spec:
  type: NodePort
  selector:
    app: sgl-market-intelligence
  ports:
    - protocol: TCP
      port: 7010
      targetPort: 7010
      nodePort: 30010
