apiVersion: v1
kind: Secret
metadata:
  name: sgl-secrets
type: Opaque
stringData:
  SERPAPI_KEYS: "1e340dbe9e098ae77e0a281b4db39808a3c6c0bde0d14bfce5c030c324ef1c7d"
  GOV_BR_USER: "99490021334"
  GOV_BR_PASS: "jvpn1234"

