export const CATALOGO_PRODUTOS: Record<string, string[]> = {
  "CEREAIS E GÊNEROS ALIMENTÍCIOS": [
    "Arroz branco tipo 1 – 1 kg",
    "Arroz parboilizado – 1 kg",
    "Feijão carioca – 1 kg",
    "Feijão de corda – 1 kg",
    "Feijão preto – 1 kg",
    "Milho para mungunzá",
    "Milho para pipoca",
    "Flocão de milho – 500 g",
    "Fubá de milho",
    "Canjiquinha",
    "Aveia em flocos – 200 g",
    "Aveia em flocos – 500 g",
    "Aveia em flocos finos",
    "Farinha de milho",
    "Farinha de mandioca",
    "Farinha de trigo",
    "Goma de tapioca",
    "Açúcar cristal – 1 kg",
    "Café torrado e moído – 250 g",
    "Café torrado e moído – 500 g",
    "Leite em pó – 200 g",
    "Leite em pó – 400 g",
    "Leite em pó – 800 g",
    "Biscoito cream cracker",
    "Biscoito maisena",
    "Biscoito wafer",
    "Biscoito doce",
    "Barra de cereal",
    "Achocolatado em pó",
    "Achocolatado pronto - 200ml",
    "Suco em pó",
    "Suco pronto/Tetra Pak - 200ml",
    "Polpa de frutas",
    "Óleo de soja",
    "Margarina",
    "Sardinha em lata",
    "Extrato de tomate",
    "Macarrão",
    "Sal refinado"
  ],
  "HIGIENE E BELEZA": [
    "Sabonete em barra",
    "Sabonete líquido",
    "Shampoo",
    "Condicionador",
    "Creme dental",
    "Escova dental",
    "Fio dental",
    "Enxaguante bucal",
    "Desodorante",
    "Algodão",
    "Cotonete",
    "Papel higiênico",
    "Papel higiênico folha dupla",
    "Papel toalha",
    "Lenço de papel",
    "Higiene feminina",
    "Absorvente higiênico",
    "Absorvente noturno",
    "Absorvente pós-parto",
    "Protetor diário",
    "Absorvente geriátrico",
    "Creme hidratante",
    "Protetor solar",
    "Álcool em gel"
  ],
  "PRODUTOS INFANTIS": [
    "Fraldas",
    "Fralda infantil RN - Tira ajustável",
    "Fralda infantil P - Tira ajustável",
    "Fralda infantil M - Tira ajustável",
    "Fralda infantil G - Tira ajustável",
    "Fralda infantil XG - Tira ajustável",
    "Fralda infantil XXG - Tira ajustável",
    "Fralda tipo calça P",
    "Fralda tipo calça M",
    "Fralda tipo calça G",
    "Fralda tipo calça XG",
    "Fralda tipo calça XXG",
    "Higiene do bebê",
    "Lenço umedecido",
    "Sabonete infantil",
    "Shampoo infantil",
    "Condicionador infantil",
    "Creme para prevenção de assaduras",
    "Algodão",
    "Cotonetes",
    "Toalha umedecida",
    "Talco infantil",
    "Hidratante infantil"
  ],
  "PRODUTOS DE LIMPEZA": [
    "Água sanitária – 1 L",
    "Desinfetante – 500 ml",
    "Desinfetante – 1 L",
    "Desinfetante – 5 L",
    "Detergente líquido – 500 ml",
    "Detergente – 5 L",
    "Vassoura",
    "Rodo"
  ],
  "GERIÁTRICOS / INCONTINÊNCIA": [
    "Fralda geriátrica P",
    "Fralda geriátrica M",
    "Fralda geriátrica G",
    "Fralda geriátrica XG",
    "Fralda geriátrica XXG",
    "Fralda geriátrica para fluxo intenso",
    "Fralda geriátrica noturna",
    "Fralda tipo calça adulto P",
    "Fralda tipo calça adulto M",
    "Fralda tipo calça adulto G",
    "Fralda tipo calça adulto XG",
    "Fralda tipo calça adulto XXG",
    "Sabonete líquido",
    "Shampoo",
    "Luvas descartáveis",
    "Avental descartável",
    "Máscara descartável",
    "Lençol descartável"
  ],
  "DESCARTÁVEIS": [
    "Copo descartável 50ml PS",
    "Copo descartável 150ml PS",
    "Copo descartável 180ml PS",
    "Copo descartável 200ml PS",
    "Copo descartável 300ml PS",
    "Copo descartável 400 ml PS",
    "Copo descartável 50ml PP",
    "Copo descartável 150ml PP",
    "Copo descartável 180ml PP",
    "Copo descartável 200ml PP",
    "Copo descartável 300ml PP",
    "Copo descartável 400ml PP",
    "Copo para café",
    "Prato descartável pequeno",
    "Prato descartável grande",
    "Garfo descartável",
    "Faca descartável",
    "Colher descartável",
    "Colher para café",
    "Mexedor para café",
    "Marmitex de alumínio",
    "Marmitex de isopor",
    "Pote descartável",
    "Artigos de plástico",
    "Cadeira de plástico sem braço",
    "Cadeira de plástico com braço",
    "Mesa de plástico"
  ]
};

export function getCategoriaDoProduto(nomeProduto: string): string {
  if (!nomeProduto) return "OUTROS";
  const cleanNome = nomeProduto.toLowerCase().trim();
  
  for (const [categoria, produtos] of Object.entries(CATALOGO_PRODUTOS)) {
    for (const p of produtos) {
      if (cleanNome.includes(p.toLowerCase().trim()) || p.toLowerCase().trim().includes(cleanNome)) {
        return categoria;
      }
    }
  }
  return "OUTROS";
}
